trigger:
  tags:
    include:
    - v*

variables:
  # Azure Container Registry information
  ACR_REPOSITORY: investment-tracking
  ACR_REGISTRY: AzureContainerRegistry
  # Docker image information
  DOCKER_IMAGE: api
  DOCKERFILE: src/InvestmentTracking.Api/Dockerfile

stages:
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - task: Docker@2
      displayName: Build and tag Docker image and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR_REGISTRY)
        repository: $(ACR_REPOSITORY)/$(DOCKER_IMAGE)
        tags: |
          ${{ if ne(indexOf(variables['Build.SourceBranchName'], 'alpha'), -1) || ne(indexOf(variables['Build.SourceBranchName'], 'beta'), -1) }}$(Build.SourceBranchName)${{ else }}$(Build.SourceBranchName),latest${{ endif }}

        Dockerfile: $(DOCKERFILE)
        buildContext: src