trigger:
  tags:
    include:
    - v*

variables:
  # Azure Container Registry information
  ACR_REPOSITORY: investment-tracking
  ACR_REGISTRY: exoftdocker.azurecr.io
  # Docker image information
  DOCKER_IMAGE: investment-tracking-api
  DOCKERFILE: InvestmentTracking.Api/Dockerfile

stages:
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - task: Docker@2
      displayName: Build and tag Docker image
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR_REGISTRY)
        repository: $(ACR_REPOSITORY)/$(DOCKER_IMAGE)
        tags: |
          $(Build.SourceBranchName)
        Dockerfile: $(DOCKERFILE)

- stage: Deploy
  displayName: Deploy Docker image to Azure Container Registry
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy Docker image to Azure Container Registry
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - task: Docker@2
      displayName: Push Docker image to Azure Container Registry
      inputs:
        command: push
        containerRegistry: $(ACR_REGISTRY)
        repository: $(ACR_REPOSITORY)/$(DOCKER_IMAGE)
        tags: |
          $(Build.SourceBranchName)