trigger:
  tags:
    include:
    - v*

variables:
  # Azure Container Registry information
  ACR_REPOSITORY: investment-tracking
  ACR_REGISTRY: AzureContainerRegistry
  # Docker image information
  DOCKER_IMAGE: api
  DOCKERFILE: src/InvestmentTracking.Api/Dockerfile

stages:
- stage: Test
  displayName: Run unit tests
  jobs:
  - job: Test
    displayName: Run unit tests
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - task: DotNetCoreCLI@2
      displayName: Restore dependencies
      inputs:
        command: restore
        projects: |
          **/*.csproj
    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: build
        projects: |
          **/*.csproj
    - task: DotNetCoreCLI@2
      displayName: Run unit tests
      inputs:
        command: test
        projects: |
          **/*Tests.csproj
        arguments: '--configuration Release --filter Category!=Integration'

- stage: Build 
  dependsOn: Test
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      submodules: recursive
    - task: Docker@2
      displayName: Build and tag Docker image and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR_REGISTRY)
        repository: $(ACR_REPOSITORY)/$(DOCKER_IMAGE)
        tags: |
          $(Build.SourceBranchName)

        Dockerfile: $(DOCKERFILE)
        buildContext: src