version: '3.4'

services:
  investment-tracking-api:
    image: ${DOCKER_REGISTRY-}investment-tracking-api
    build:
      context: .
      dockerfile: InvestmentTracking.Api/Dockerfile
    depends_on:
      - investment-tracking-sql
  investment-tracking-sql:
    image: mcr.microsoft.com/mssql/server:${SQL_SERVER_TAG}
    container_name:  investment-tracking-sql
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "M1llions2023"
      ACCEPT_EULA: "Y"
    volumes:
      - ./volumes/sql/data:/var/opt/mssql/data